---

postgresql:
  primary:
    persistence:
      existingClaim: ""
  livenessProbe:
    initialDelaySeconds: 200
    initialDelaySeconds: 200
  volumePermissions:
    enabled: true
  global:
    postgresql:
      auth:
        username: "airflow"
        database: "airflow"
        existingSecret: pgsql-secrets
        # secretKeys:
        #   adminPasswordKey: postgres-password
        #   userPasswordKey: password
        #   replicationPasswordKey: replication-password
  # auth:
  #   username: "airflow"
  #   database: "airflow"
  #   existingSecret: pgsql-secrets
  #   secretKeys:
  #     adminPasswordKey: postgres-password
  #     userPasswordKey: password
  #     replicationPasswordKey: replication-password

airflow:
  auth:
    username: airflow
    # password: airflow
    existingSecret: airflow-secrets

  dags:
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r34
      digest: ""
      pullPolicy: IfNotPresent
  git:
    image:
      registry: docker.io
      tag: 2.37.3-debian-11-r4
      digest: ""
      pullPolicy: IfNotPresent
    dags:
      enabled: true
      repositories:
        - repository: "https://github.com/hutger/airflow-helm.git"
          branch: "main"
          name: "iff"
          path: ""
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt
  executor: LocalExecutor

  externalDatabase:
    host: airflow-postgresql
    port: 5432
    user: airflow
    database: airflow
    existingSecret: airflow-secrets
    existingSecretPasswordKey: postgresql-password

  logs.persistence.enabled: true
  logs.persistence.existingClaim: "logs"


  ingress:
    enabled: false
    ingressClassName: nginx
    hostname: airflow.lucasalbuq.co

  serviceAccount:
    create: true
    name: "airflow"
    automountServiceAccountToken: true

  redis:
    enabled: false

  postgresql:
    enabled: false

  rbac:
    create: true
